### ISSUE TITLE
Icon gets changed in editor, but stays 'Home' icon, in code generated by GrapesJs.

### ISSUE THREAD

**Issue by Fahad-ishfaq** [edenizk/grapesjs-google-material-icons#20]
**Issue:** Icon gets changed in editor, but stays 'Home' icon, in code generated by GrapesJs.
![image](https://github.com/edenizk/grapesjs-google-material-icons/assets/74470297/67795a16-87e9-43a7-ba68-0d9bfcc10a57)

![image](https://github.com/edenizk/grapesjs-google-material-icons/assets/74470297/2461b263-a10c-4405-8ea5-54682ebedbe5)

**Comment by edenizk** [comment]
Hi @Fahad-ishfaq,

First of all thank you for using this package and giving me a feedback 🙂

I have added the fix for the issue, you can test it on demo project.
Or by updating your package to version 1.0.9 🙂

Let me know if everything is alright, so I can close the issue.

**Comment by Fahad-ishfaq** [comment]
Hi @edenizk,
Yes, it is working now. You can close it.

Thanks for immediate response really appreciate it!
